import { defineCollection, z } from 'astro:content';

// Insights (blog) — migrated from the Webflow "Blog Posts" collection.
// One .md per post at src/content/insights/<slug>.md: YAML frontmatter (metadata)
// plus the post body as raw HTML. Generated by scripts/csv-to-insights.mjs, which
// also documents the Webflow-column -> field mapping. The post template renders the
// body with set:html, so the HTML is never run through Markdown.
const insights = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),                         // Webflow: Name
    description: z.string().optional(),         // Webflow: Snippet  (meta + card excerpt)
    summary: z.string().optional(),            // Webflow: Post Summary (kept, not displayed)
    publishedAt: z.coerce.date().optional(),   // Webflow: Published On (re-import dates; not shown)
    coverImage: z.string().optional(),         // R2 main image (post hero + social card)
    thumbnail: z.string().optional(),          // R2 thumbnail (overview cards)
    sources: z.string().optional(),            // Sources / image credits HTML block
    featured: z.boolean().default(false),      // Webflow: Featured?
    readTime: z.string().optional(),           // computed, e.g. "8 min read"
    draft: z.boolean().default(false),
  }),
});

// PHASE 3 (deferred) — finalised when we migrate the Webflow Customer Stories CMS.
const customerstories = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    company: z.string().optional(),
    summary: z.string().optional(),
    logo: z.string().optional(),
    metrics: z.array(z.string()).optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { insights, customerstories };
