import { defineCollection, z } from 'astro:content';

// Insights (blog) — migrated from the Webflow "Blog Posts" collection.
// One .md per post at src/content/insights/<slug>.md: YAML frontmatter (metadata)
// plus the post body as raw HTML. Generated by scripts/csv-to-insights.mjs, which
// also documents the Webflow-column -> field mapping. The post template renders the
// body with set:html, so the HTML is never run through Markdown.
const insights = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),                         // Webflow: Name
    description: z.string().optional(),         // Webflow: Snippet  (meta + card excerpt)
    summary: z.string().optional(),            // Webflow: Post Summary (kept, not displayed)
    publishedAt: z.coerce.date().optional(),   // Webflow: Published On (re-import dates; not shown)
    coverImage: z.string().optional(),         // R2 main image (post hero + social card)
    thumbnail: z.string().optional(),          // R2 thumbnail (overview cards)
    sources: z.string().optional(),            // Sources / image credits HTML block
    featured: z.boolean().default(false),      // Webflow: Featured?
    readTime: z.string().optional(),           // computed, e.g. "8 min read"
    cta: z.string().optional(),                // optional custom trial-CTA line (overrides the default)
    draft: z.boolean().default(false),
  }),
});

// Customer stories — migrated from the Webflow "Customer Stories" collection.
// One .md per story at src/content/customerstories/<slug>.md: YAML frontmatter
// plus the story body as raw HTML. Generated by scripts/csv-to-customerstories.mjs.
// The template renders the body with set:html, so the HTML is never run through Markdown.
const customerstories = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),                          // Webflow: Name
    description: z.string().optional(),          // Webflow: Snippet (meta + card excerpt)
    company: z.string().optional(),             // Webflow: Customer name
    champion: z.string().optional(),            // Webflow: Customer champion (person quoted)
    championTitle: z.string().optional(),       // Webflow: Customer champion title (their role)
    championImage: z.string().optional(),       // champion photo (R2 avatar, or source until on R2)
    testimonial: z.string().optional(),         // Webflow: Testimonial (pull quote)
    results: z.array(z.object({                 // Webflow: Result 1/2/3 metric + name
      metric: z.string(),
      label: z.string(),
    })).optional(),
    cta: z.string().optional(),                 // optional custom trial-CTA line (overrides the default)
    draft: z.boolean().default(false),
  }),
});

export const collections = { insights, customerstories };
