import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

// Insights (blog) — migrated from the Webflow "Blog Posts" collection.
// One .md per post at src/content/insights/<slug>.md: YAML frontmatter (metadata)
// plus the post body as raw HTML. Generated by scripts/csv-to-insights.mjs, which
// also documents the Webflow-column -> field mapping. The post template renders the
// body with set:html, so the HTML is never run through Markdown.
const insights = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/insights' }),
  schema: z.object({
    title: z.string(),                         // Webflow: Name
    description: z.string().optional(),         // Webflow: Snippet  (meta + card excerpt)
    summary: z.string().optional(),            // Webflow: Post Summary (kept, not displayed)
    publishedAt: z.coerce.date().optional(),   // Webflow: Published On (re-import dates; not shown)
    coverImage: z.string().optional(),         // R2 main image (post hero + social card)
    thumbnail: z.string().optional(),          // R2 thumbnail (overview cards)
    sources: z.string().optional(),            // Sources / image credits HTML block
    featured: z.boolean().default(false),      // Webflow: Featured?
    readTime: z.string().optional(),           // computed, e.g. "8 min read"
    cta: z.string().optional(),                // optional custom trial-CTA line (overrides the default)
    topics: z.array(z.string()).default([]),   // topic tags: related posts + hub links
    draft: z.boolean().default(false),
  }),
});

// Knowledge center (/knowledge) — the product help section for app.hubsell.com
// users. One .md per article at src/content/knowledge/<slug>.md: YAML frontmatter
// (metadata) plus the article body as raw HTML (steps, figures, result), rendered
// with set:html by src/pages/knowledge/[slug].astro. Drafts are authored in the
// Confluence space (HKB); at publish the approved article moves here and the repo
// becomes the source of truth. Screenshots are rehosted under knowledge/ on the
// asset store — do not hotlink Scribe's servers from a shipped article.
const knowledge = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/knowledge' }),
  schema: z.object({
    title: z.string(),                          // article H1 + <title>
    description: z.string().optional(),         // meta + hub card excerpt
    category: z.string(),                       // e.g. "Getting started" (eyebrow + hub group)
    order: z.number().default(0),               // sort order within its category on the hub
    series: z.string().optional(),              // onboarding series name, if part of one
    seriesStep: z.number().optional(),          // this article's position in the series
    seriesTotal: z.number().optional(),         // total steps in the series
    estMinutes: z.number().optional(),          // time estimate shown in the meta row
    stepCount: z.number().optional(),           // number of steps, shown in the meta row
    walkthroughUrl: z.string().optional(),      // Scribe viewer URL: click-to-load embed
    next: z.object({ label: z.string(), href: z.string() }).optional(), // next-in-series card
    draft: z.boolean().default(false),
  }),
});

// Customer stories — migrated from the Webflow "Customer Stories" collection.
// One .md per story at src/content/customerstories/<slug>.md: YAML frontmatter
// plus the story body as raw HTML. Generated by scripts/csv-to-customerstories.mjs.
// The template renders the body with set:html, so the HTML is never run through Markdown.
const customerStorySchema = z.object({
    title: z.string(),                          // Webflow: Name
    description: z.string().optional(),          // Webflow: Snippet (meta + card excerpt)
    company: z.string().optional(),             // Webflow: Customer name
    champion: z.string().optional(),            // Webflow: Customer champion (person quoted)
    championTitle: z.string().optional(),       // Webflow: Customer champion title (their role)
    championImage: z.string().optional(),       // champion photo (R2 avatar, or source until on R2)
    testimonial: z.string().optional(),         // Webflow: Testimonial (pull quote)
    results: z.array(z.object({                 // Webflow: Result 1/2/3 metric + name
      metric: z.string(),
      label: z.string(),
    })).optional(),
    cta: z.string().optional(),                 // optional custom trial-CTA line (overrides the default)
    draft: z.boolean().default(false),
});

const customerstories = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/customerstories' }), schema: customerStorySchema });
// German customer stories: same schema, parallel folder src/content/customerstoriesDe/<slug>.md,
// same slugs as the English entries.
const customerstoriesDe = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/customerstoriesDe' }), schema: customerStorySchema });
// Dutch customer stories: same schema, parallel folder src/content/customerstoriesNl/<slug>.md,
// same slugs as the English entries.
const customerstoriesNl = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/customerstoriesNl' }), schema: customerStorySchema });

// Comparisons (/vs pages) — migrated from the Webflow "Comparisons" collection.
// One .md per competitor at src/content/comparisons/<slug>.md. Unlike the blog and
// stories, a comparison is NOT one rich-text body: it's a set of named sections, so
// each maps to its own frontmatter field (mostly raw HTML, rendered with set:html).
// Generated by scripts/csv-to-comparisons.mjs. Build ALL rows — these are launch
// pages drafted in Webflow, so the template does not filter on `draft`.
const comparisonSchema = z.object({
    title: z.string(),                          // Webflow: Name (competitor, e.g. "Apollo")
    category: z.string().optional(),            // Webflow: Competitor category (e.g. "All-in-one")
    competitorLogo: z.string().optional(),      // Webflow: Competitor logo (R2 url; empty for now)
    hubsellLogo: z.string().optional(),         // Webflow: hubsell logo (R2 url; empty for now)
    metaTitle: z.string().optional(),           // Webflow: Meta title (SEO <title>)
    metaDescription: z.string().optional(),     // Webflow: Meta description (SEO)
    heroSubhead: z.string().optional(),         // Webflow: Hero subhead (plain text intro)
    tldr: z.string().optional(),                // Webflow: TL;DR (HTML)
    coreDifference: z.string().optional(),      // Webflow: Core difference (HTML)
    featureTable: z.string().optional(),        // Webflow: Feature table (HTML, .hs-cmp table)
    dataQuality: z.string().optional(),         // Webflow: Data quality (HTML)
    pricing: z.string().optional(),             // Webflow: Pricing comparison (HTML)
    chooseCompetitor: z.string().optional(),    // Webflow: Who should choose the competitor (HTML)
    chooseHubsell: z.string().optional(),       // Webflow: Who should choose hubsell (HTML)
    ctaHeading: z.string().optional(),          // Webflow: CTA heading
    ctaButtonText: z.string().optional(),       // Webflow: CTA button text
    ctaLink: z.string().optional(),             // Webflow: CTA link (e.g. /book-a-call)
    lastFactChecked: z.string().optional(),     // Webflow: Last fact-checked (formatted date)
    sources: z.string().optional(),             // Webflow: Sources (HTML)
    draft: z.boolean().default(false),
});

const comparisons = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/comparisons' }), schema: comparisonSchema });
// German comparisons: same schema, parallel folder src/content/comparisonsDe/<slug>.md,
// same slugs as the English entries.
const comparisonsDe = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/comparisonsDe' }), schema: comparisonSchema });
// Dutch comparisons: same schema, parallel folder src/content/comparisonsNl/<slug>.md,
// same slugs as the English entries.
const comparisonsNl = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/comparisonsNl' }), schema: comparisonSchema });

// Use-cases — authored in Astro (no Webflow source). One .md per use-case at
// src/content/usecases/<slug>.md: frontmatter for the hero, the featured proof
// story, the key features and roles, plus the page body as Markdown. Rendered the
// normal way (render() + <Content />), not set:html, so the body is real Markdown.
const usecaseSchema = z.object({
  title: z.string(),                        // H1
  label: z.string().optional(),             // short name for cards / nav
  eyebrow: z.string().optional(),           // category label above the H1
  metaTitle: z.string().optional(),         // SEO <title> (falls back to title)
  description: z.string().optional(),       // SEO meta + card excerpt
  subhead: z.string().optional(),           // hero intro
  widget: z.string().optional(),            // product widget component to render as the page visual
  widgetBg: z.string().optional(),          // section class for the widget band (e.g. "sec--navy")
  widgetCaption: z.string().optional(),     // short line above the widget
  proofStory: z.string().optional(),        // customer-story slug to feature as proof
  features: z.array(z.string()).optional(), // key feature labels
  roles: z.array(z.string()).optional(),    // who it's for (labels)
  related: z.array(z.string()).optional(),  // related use-case slugs
  quotes: z.array(z.string()).optional(),   // testimonial slugs for the proof strip
  ctaHeading: z.string().optional(),        // optional CTA heading override
  ctaText: z.string().optional(),           // optional CTA body override
  order: z.number().default(99),            // overview sort order
  draft: z.boolean().default(false),
});

const usecases = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/usecases' }), schema: usecaseSchema });
// German use-cases: same schema, parallel folder. src/content/usecasesDe/<slug>.md
// uses the SAME slug as its English counterpart so the two map one to one.
const usecasesDe = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/usecasesDe' }), schema: usecaseSchema });
// Dutch use-cases: same schema, parallel folder src/content/usecasesNl/<slug>.md,
// same slugs as the English entries.
const usecasesNl = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/usecasesNl' }), schema: usecaseSchema });


// One .md per term at src/content/glossary/<slug>.md (+ glossaryDe / glossaryNl).
// The 4 written sections live in the markdown BODY as H2s (Why it matters, How it
// works in practice, Common mistakes, How hubsell approaches it). Frontmatter holds
// the identity, the one-sentence definition (the quotable GEO answer under the H1),
// the category, and the related term slugs (the related block is auto-rendered).
const glossarySchema = z.object({
    term: z.string(),                      // display name, e.g. "Data enrichment"
    category: z.string(),                  // one of the 8 glossary categories
    definition: z.string(),                // one clear sentence, sits under the H1
    related: z.array(z.string()).default([]), // other term slugs
    updated: z.string().optional(),        // formatted date, e.g. "July 2026"
    draft: z.boolean().default(false),
});

const glossary = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/glossary' }), schema: glossarySchema });
const glossaryDe = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/glossaryDe' }), schema: glossarySchema });
const glossaryNl = defineCollection({ loader: glob({ pattern: '**/*.md', base: './src/content/glossaryNl' }), schema: glossarySchema });

export const collections = { insights, knowledge, customerstories, customerstoriesDe, customerstoriesNl, comparisons, comparisonsDe, comparisonsNl, usecases, usecasesDe, usecasesNl, glossary, glossaryDe, glossaryNl };
